# Defaults
inactive-opacity = 0.98;
active-opacity = 1;

#backend = "xrender";
backend = "glx";
#xrender-sync-fence=true;

vsync = true;


# Custom opacity for terminal
opacity-rule = [
  "95:class_g = 'kitty' && focused",
  "85:class_g = 'kitty' && !focused"
];

shadow = true;

# The blur radius for shadows, in pixels. (defaults to 12)
shadow-radius = 20;

# The opacity of shadows. (0.0 - 1.0, defaults to 0.75)
#shadow-opacity = 0.85
shadow-opacity = 0.75

#shadow-opacity = 0.8;
#shadow-offset-x = 4;
#shadow-offset-y = 4;


shadow-exclude = [
  "class_g = 'flameshot'",
];

focus-exclude = [
  "class_g = 'flameshot'",
];

