# Defaults
inactive-opacity = 1;
active-opacity = 1;

# SHADOWS
#_----------
shadow = true;

# The blur radius for shadows, in pixels. (defaults to 12)
shadow-radius = 20;

# The opacity of shadows. (0.0 - 1.0, defaults to 0.75)
#shadow-opacity = 0.85
shadow-opacity = 0.75

# Custom opacity for terminal
opacity-rule = [
  "85:class_g = 'kitty' && focused",
  "75:class_g = 'kitty' && !focused"
];

backend = "glx";

blur:
{
  method = "dual_kawase";
  strength = 5;
};

blur-background = true;
blur-background-frame = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
